/**
 * n8n Incoming Webhook Handler
 * POST /api/webhooks/n8n
 *
 * n8n calls this endpoint to:
 * - Deliver AI-generated content back to our app
 * - Update post statuses after publishing
 * - Create notifications
 * - Log workflow results
 *
 * SECURITY: Validates X-Webhook-Secret header before processing.
 */

import { NextRequest } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function POST(request: NextRequest) {
  try {
    // Verify the request comes from n8n
    const secret = request.headers.get('x-webhook-secret');
    if (secret !== process.env.N8N_INCOMING_SECRET) {
      console.warn('[webhook/n8n] Invalid secret received');
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { event, data } = body;

    console.log(`[webhook/n8n] Received event: ${event}`);

    switch (event) {
      // ============================================================
      // AI Caption delivered back from n8n
      // ============================================================
      case 'ai.caption.result': {
        const { postId, caption, hashtags, contentScore, summary } = data;
        if (!postId) break;

        await prisma.post.update({
          where: { id: postId },
          data: { caption, hashtags, contentScore, aiSummary: summary },
        });

        break;
      }

      // ============================================================
      // Post published by n8n scheduler
      // ============================================================
      case 'post.published': {
        const { postId, userId, success, error } = data;
        if (!postId) break;

        await prisma.post.update({
          where: { id: postId },
          data: {
            status: success ? 'PUBLISHED' : 'FAILED',
            publishedAt: success ? new Date() : undefined,
          },
        });

        if (userId) {
          await prisma.notification.create({
            data: {
              userId,
              title: success ? '✅ Post Published!' : '❌ Publishing Failed',
              message: success
                ? `Your scheduled post has been published successfully.`
                : `Failed to publish your post. Error: ${error || 'Unknown error'}. Please try again.`,
              type: success ? 'SUCCESS' : 'ERROR',
              actionUrl: '/content',
            },
          });

          await prisma.activity.create({
            data: {
              userId,
              type: 'POST_PUBLISHED',
              description: success
                ? `Scheduled post published successfully`
                : `Scheduled post failed to publish`,
              metadata: { postId, success, error },
            },
          });
        }
        break;
      }

      // ============================================================
      // Weekly report generated by n8n
      // ============================================================
      case 'report.weekly.complete': {
        const { userId, reportUrl, summary: reportSummary } = data;
        if (!userId) break;

        await prisma.notification.create({
          data: {
            userId,
            title: '📊 Weekly Report Ready',
            message: reportSummary || 'Your weekly analytics report has been generated.',
            type: 'INFO',
            actionUrl: reportUrl || '/analytics',
          },
        });

        await prisma.activity.create({
          data: {
            userId,
            type: 'ANALYTICS_REPORT',
            description: 'Weekly analytics report generated by n8n',
            metadata: { reportUrl },
          },
        });
        break;
      }

      // ============================================================
      // Workflow triggered notification
      // ============================================================
      case 'workflow.triggered': {
        const { userId, workflowName, postId: wfPostId } = data;
        if (userId && wfPostId) {
          await prisma.activity.create({
            data: {
              userId,
              type: 'WORKFLOW_TRIGGERED',
              description: `n8n workflow "${workflowName}" triggered`,
              metadata: data,
            },
          });
        }
        break;
      }

      default:
        console.log(`[webhook/n8n] Unknown event: ${event}`);
    }

    return Response.json({ data: { received: true, event } });
  } catch (error) {
    console.error('[webhook/n8n] Error:', error);
    return Response.json({ error: 'Webhook processing failed' }, { status: 500 });
  }
}
